### ISSUE TITLE
Doesn't seem to work on any platform other than Nexus 5x

### ISSUE THREAD

**Issue by cansacha** [nfcgate/nfcgate#113]
Has anyone tested on a device other than the Nexus 5? I tried on a BCN2079X chip and on a PN66T but couldn't get the relay mode to work. No player commands are read by the app.

**Comment by kleest** [comment]
The [compatibility document](https://github.com/nfcgate/nfcgate/blob/v2/doc/Compatibility.md) shows devices confirmed working on the latest `v2` branch commit. In addition, any NFC-capable Android device that fulfills the requirements supports **reader role** in relay mode, even without root access because this is basic Android functionality. For example, we had great success using a stock OnePlus 6 in reader role for relay mode. The only feature, which explicitly requires a rooted system and could have compatibility issues, is cloning initial/static tag data data, such as `NFCID`.

Could you provide us more information about your setup, your devices, your software versions? Logs help, too.
