### ISSUE TITLE
Warning: Xposed module is not working properly

### ISSUE THREAD

**Issue by Ryuo1** [nfcgate/nfcgate#131]
But the module is enabled.
Device: Samsung S8+ with custom Android 10 OneUI 2.5 mod
LSPosed info:
```
API version
100

Xposed API call protection
Enabled

Dex Optimizer Wrapper
Unsupported (SELinux is permissive)

Framework version
1.9.1 (6990)

Manager package name
com.android.shell

System version
10 (API 29)

Device
Samsung SM-N960N 

System ABI
arm64-v8a
```
![Screenshot_(46)_SM-N960N_2023 09 04-14 26 11](https://github.com/nfcgate/nfcgate/assets/77712873/7c3ffaf7-f3cb-4956-b3b6-8f7aae19213b)
![image](https://github.com/nfcgate/nfcgate/assets/77712873/e9aad4c0-adff-43c3-9701-949092604b73)
![image](https://github.com/nfcgate/nfcgate/assets/77712873/2a6e86fd-e504-485b-af5b-e393b53cd488)
![image](https://github.com/nfcgate/nfcgate/assets/77712873/d3ce0d5b-58a0-49cc-a6b0-7c80720e9fd1)
![image](https://github.com/nfcgate/nfcgate/assets/77712873/a9968934-9af4-4b2d-a90a-15e14a683918)
![image](https://github.com/nfcgate/nfcgate/assets/77712873/6d057b4b-3b2a-417b-9591-ace4ff617722)

ADB logcat after boot:
[logcat.txt](https://github.com/nfcgate/nfcgate/files/12512146/logcat.txt)

**Comment by roussosalex** [comment]
Thanks for reporting this issue. We were slightly confused by your device identifying as a Samsung Galaxy Note 9 when you said it was a Samsung Galaxy S8+, which seems to be due to the OneUI mod ROM. We have attached an experimental "Samsung" version based on bea61ddb688b4a1f2961dacddaa8f88c7d3f096c. It allows to delay the hooking process, which seems to be the issue with your device.

Please give it a try and report back if it works and if it is now able to detect your NFC chip on the status page.
[nfcgate-samsung-debug.zip](https://github.com/nfcgate/nfcgate/files/12591896/nfcgate-samsung-debug.zip)

**Comment by Ryuo1** [comment]
It detects the LSposed module now, but the Native Hook still returns 'No'
![Screenshot_20230913-151429_NFCGate.png](https://github.com/nfcgate/nfcgate/assets/77712873/dd3d0710-1906-4c6d-b6b4-138e66bbdde1)

**Comment by Gabboxl** [comment]
Hi, I am running the same OneUI mod ROM on my Galaxy S8 and in fact, my device is identified as a Galaxy Note 9 from other apps also. 
I'm experiencing the same problem with the Native hook.

**Comment by kleest** [comment]
Thanks for testing! Could you attach a logcat from boot to start of NFCGate app, please?

**Comment by Ryuo1** [comment]
I am sorry for the delay, here I have attached the logs:
![Log_2023-9-14_10-29-48.txt](https://github.com/nfcgate/nfcgate/files/12604948/Log_2023-9-14_10-29-48.txt)

**Comment by kleest** [comment]
@ryu0q Unfortunately, the log is incomplete and misses the relevant hooking logs :slightly_frowning_face:. Please capture it shortly after the device start so it is not truncated because of the limited log buffer. As an alternative to restarting the device, you can also kill the NFC service via a root shell: `killall com.android.nfc`

**Comment by Ryuo1** [comment]
[logcat.txt](https://github.com/nfcgate/nfcgate/files/12622891/logcat.txt)

Sorry for the delay caused again, I have now attached the logs using the `adb logcat -d` command. I hope this has the complete information. Feel free to ask me for new logs again if these aren't the right ones, or if I captured them wrong.

**Comment by roussosalex** [comment]
Unfortunately, the log is still incomplete. The log should contain the tag `NATIVENFC` with the line `Library found at`, as your first log does but your second and third are missing this part. It may be that the log is going too fast and these lines were dropped by logcat, so you could try:

1. Running logcat on the device directly via `adb shell "logcat > /sdcard/log.txt"`. This should record the log directly on the device and does not need to transfer everything via adb.
2. You could also try killing the nfc process at a less busy time in a root shell: `killall com.android.nfc`, wait a few seconds, then use the `adb logcat -d` command to dump the logs. Since this is nowhere near boot, the log should be less busy and not skip anything.

**Comment by dmunozv04** [comment]
Hello, I'm also experiencing the same issue with a S8. I've attached the logs gathered by `logcat` after killing the nfc service. I'm using the experimental samsung version.
[log.txt](https://github.com/nfcgate/nfcgate/files/12643126/log.txt)

**Comment by Ryuo1** [comment]
This one has that line:
[log.txt](https://github.com/nfcgate/nfcgate/files/12643215/log.txt)

**Comment by roussosalex** [comment]
Thanks for posting the log, it really helped. We have made some small adjustments and have attached a new experimental version based on bba040eab3f95b9dab4da52a211a002f660691e3. 

Please give it a try and report back if it works, if it does not work please also attach a boot log with the  `NATIVENFC` line as last time.
[nfcgate-samsung-debug-v2.zip](https://github.com/nfcgate/nfcgate/files/12644033/nfcgate-samsung-debug-v2.zip)

**Comment by Ryuo1** [comment]
Not working
![log.txt](https://github.com/nfcgate/nfcgate/files/12644161/log.txt)

**Comment by roussosalex** [comment]
The log seems to show native hook success now. Try force-stopping NFCGate and opening it back up to make sure the status page is up to date.

**Comment by Ryuo1** [comment]
I totally forgot to do that. Sorry for wasting your time :p
It's working now. Thank you all so much!!

**Comment by roussosalex** [comment]
Thanks for testing! Could you check if the hook also works if you open NFCGate for the first time after reboot, just to be sure?

**Comment by Ryuo1** [comment]
it does!

**Comment by mr7Ouroboros** [comment]
Hello, I'm experiencing the same problem with the Native hook.
Samsung SM-J730FM/DS
I tried to force stop NFCGate and open it again, but nothing changed.
Please help me solve the problem. 
![photo_2024-01-25_21-26-53 (4)](https://github.com/nfcgate/nfcgate/assets/157714640/dd79cfa9-3219-4ba4-b369-8ade3cf2533f)
![photo_2024-01-25_21-26-53 (2)](https://github.com/nfcgate/nfcgate/assets/157714640/59f9707b-fbcb-4031-a0d9-b4025262b144)
![photo_2024-01-25_21-26-53](https://github.com/nfcgate/nfcgate/assets/157714640/6192c365-ecc7-4f4e-a12b-c6d65b7ef072)
![photo_2024-01-25_21-26-52](https://github.com/nfcgate/nfcgate/assets/157714640/49ed02a0-5253-4d8d-bc40-186b744c81c8)

**Comment by mr7Ouroboros** [comment]
Here are my logs
[log.txt](https://github.com/nfcgate/nfcgate/files/14057191/log.txt)

**Comment by roussosalex** [comment]
Hello, you are most likely experiencing #141, we are working on a solution. Please open up a new issue next time.

**Comment by mr7Ouroboros** [comment]
Okay, thank you.
