### ISSUE TITLE
Not Working on Samsung S22 (Android 14) but Status All Green

### ISSUE THREAD

**Issue by IPFSae** [nfcgate/nfcgate#165]
**Describe the bug**

1. In **Clone Mode**, it showed red error message: "Error: NFC is disabled or unsupported". And no data show in the "Saved:" area.

2. In **Relay Mode**, information can be relayed to another phone successfully, but there won't be any data transmit while tap the relay phone tag on a reader.

3. Other mode not tested...

**Device Information*** 

Device: Samsung Galaxy S22

OS: Android 14 (One UI 6.1)

**Log***

Attach a boot log (system logcat since boot).

**Steps to reproduce**

N/A

**Proposed solution**

I didn't test on more phone yet... maybe Samsung S22 is not supported ?

**Comment by Lassie111** [comment]
You can try the debug version from this [comment](https://github.com/nfcgate/nfcgate/issues/153#issuecomment-2126152940).
I had similar issue with version 2.4.0, while the older debug version works fine for me.

I was going to open an issue about this, but didn't have much time recently.

**Comment by kleest** [comment]
Thanks for the report! The service crash is fixed with newest release [2.4.2](https://github.com/nfcgate/nfcgate/releases/tag/v2.4.2). The problem was a function callback that went out-of-scope. This did not cause issues in the debug version but only in the release build. Sorry!

This should fix the problem that wrong data is displayed and transported to the other phone. If I understood your setup correctly, the phone you are using to emulate the tag and tap against the POS machine is a non-rooted phone, am I right? This might not work, because such a phone cannot emulate NFCID, HIST and other parameters (static tag data). You should swap the phones. Reading all of this data with the reader phone does not require root, however, emulation does.

**Comment by IPFSae** [comment]
> Thanks for the report! The service crash is fixed with newest release [2.4.2](https://github.com/nfcgate/nfcgate/releases/tag/v2.4.2). The problem was a function callback that went out-of-scope. This did not cause issues in the debug version but only in the release build. Sorry!
> 
> This should fix the problem that wrong data is displayed and transported to the other phone. If I understood your setup correctly, the phone you are using to emulate the tag and tap against the POS machine is a non-rooted phone, am I right? This might not work, because such a phone cannot emulate NFCID, HIST and other parameters (static tag data). You should swap the phones. Reading all of this data with the reader phone does not require root, however, emulation does.

Thanks. NFC error Issue fixed on my phone. I can copy and replay UID cards now. But relay to a POS still be a challenge even after swipe. I believe in POS system there are some functions to avoid such relay...
