### ISSUE TITLE
LG ThinQ 5G Verizon native hook not enabled

### ISSUE THREAD

**Issue by NgoHuy** [nfcgate/nfcgate#179]
**App Information***

<img width="287" alt="image" src="https://github.com/user-attachments/assets/9e048086-5975-4a44-ae3e-b2b9f3b7720b">

**Device Information*** Which device are you using and what OS are you running on it?

Device:  LG ThinQ 5G

OS: android 12

**Log***

<img width="2043" alt="image" src="https://github.com/user-attachments/assets/e94370ce-1714-4e43-831c-638ef4455f23">

**Additional context**

I didnot see any NATIVENFC log on my device, I build latest v2 branch, reboot did not help

**Comment by roussosalex** [comment]
Thanks for contributing! Please try the newest commit and report back, it should now work with your LG device as well.

**Comment by NgoHuy** [comment]
it failed for native nfc.
<img width="1542" alt="image" src="https://github.com/user-attachments/assets/ce5e0abe-da87-4bf1-9834-ce0f24b6b21f">

**Comment by kleest** [comment]
@NgoHuy Can you please show logs containing NATIVENFC?

**Comment by imyxh** [comment]
Same issue on alphalm (LG G8 ThinQ) on v2.4.4. Output of `logcat | grep NFC` attached.

I think libnfc is one of these (both attached):

```
/system/system_ext/lib64/libLGnfc_nxp_jni.lge.so
/system/system_ext/lib64/libnfc-nxp-nci.lge.so
```

but it seems neither is picked up as a candidate to findLibNFC.

[libnfc.zip](https://github.com/user-attachments/files/18427868/libnfc.zip)

[nfc.log](https://github.com/user-attachments/files/18427852/nfc.log)

Fwiw I could find these by simply scanning /proc/*/maps, so that might be a more robust option to scan for libs instead of whatever is currently happening.
